### ISSUE TITLE
Test framework quit unexpectedly

### ISSUE THREAD

**Issue by swayam18** [jasmine/IdeaJasmine#2]
First of, thank you for this plugin, it makes it much simpler to run tests and encourages me to write more.

While I can run the tests on WebStorm, it does not capture the outcome of the tests correctly and always reports that the "Test framework quit unexpectedly". 

Do you know what might be causing this issue? Thanks.

**Comment by slackersoft** [comment]
What version of Jasmine are you using. The plugin only supports Jasmine 3.0 and later since that version introduces the ability to specify a reporter on the command line.

Any other information you have on what a failure looks like or an example suite/project would be helpful.

Thanks for using Jasmine!

**Comment by svenhaag** [comment]
I have the same issue using jasmine version 3.1.0.

**Comment by slackersoft** [comment]
Do either of you have a bit more information on what command IntelliJ is actually running, where your config files are, or any other information being printed out? I'm having a hard time reproducing the error with the information I have.

**Comment by monicajianu** [comment]
I am also getting the same error, this is the full output I get:

```
/Users/username/.nvm/versions/node/v8.9.4/bin/node "/Applications/IntelliJ IDEA.app/Contents/bin/bin/jasmine.js" "--reporter=/Users/username/Library/Application Support/IntelliJIdea2018.1/IdeaJasmine/lib/intellij_reporter.js" /Users/username/workspace/code/web-testing/spec/hello_world/test.js
module.js:540
    throw err;
    ^

Error: Cannot find module '/Applications/IntelliJ IDEA.app/Contents/bin/bin/jasmine.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by monicajianu** [comment]
@slackersoft Where exactly are the Jasmine plugin settings...? I can't find anything in my IntelliJ preferences.

**Comment by wiedzmin26** [comment]
I have the same issue using jasmine version 3.5.0.
jasmine version
jasmine v3.5.0
jasmine-core v3.5.0

All tests run correctly but I don't have a list of passed / failed tests on the left. Only the inscription "Test framework quit unexpected".
![Zrzut ekranu 2020-02-21 o 23 12 45](https://user-images.githubusercontent.com/52349575/75076293-1641e680-5500-11ea-95e2-e9652114b4f0.png)

@slackersoft Can you help?

**Comment by wiedzmin26** [comment]
@swayam18 @slackersoft @svenhaag @monicajianu 
I found the problem and it is:
`jasmine.getEnv().clearReporters(); ` in file
`spec/helpers/reporter.js`.

You must comment on all the `jasmine.getEnv().clearReporters();` lines from your code because they remove the necessary reporter in `/Users/USER/Library/Application Support/WebStorm2019.3/IdeaJasmine/lib/intellij_reporter.js` when running the plugin.

@slackersoft I think that there should be such information in the documentation.

In my opinion, the plugin could work better. When all the tests have passed, the whole tree of passed tests should appear, not the inscription "Test Results". I think that this can be improved in the file `/Users/USER/Library/Application Support/WebStorm2019.3/IdeaJasmine/lib/intellij_reporter.js`
